Repository cooderyg/streaming-platform, pull requests merged in 2023-08, with the labels that each got.

#1 feat: channel create, user decorator
  src/apis/channels/channels.controller.ts
  src/apis/channels/channels.module.ts
  src/apis/channels/channels.service.ts
  src/apis/channels/dto/create-channel.dto.ts
  src/app.module.ts
  src/commons/decorators/user.decorator.ts
Labels: enhancement

#2 feat: category create, findCategories
  src/apis/categories/categories.controller.ts
  src/apis/categories/categories.service.ts
  src/apis/categories/cetegories.module.ts
  src/apis/categories/dto/create-category.dto.ts
  src/apis/categories/interfaces/categories-service.interface.ts
Labels: enhancement

#3 feat: create live API
  src/apis/channels/channels.module.ts
  src/apis/channels/channels.service.ts
  src/apis/lives/dto/create-live.dto.ts
  src/apis/lives/lives.controller.ts
  src/apis/lives/lives.module.ts
  src/apis/lives/lives.service.ts
  src/app.module.ts
Labels: enhancement

#4 fix: entity & api address
  src/apis/auth/auth.controller.ts
  src/apis/lives/entities/live.entity.ts
  src/apis/users/users.controller.ts
Labels: fix

#6 feat: payment create, cancel, findOne, findMany
  src/apis/payments/dto/cancel-payment.dto.ts
  src/apis/payments/dto/create-payments.dto.ts
  src/apis/payments/entities/payment.entity.ts
  src/apis/payments/interfaces/payments-service.interface.ts
  src/apis/payments/payments.controller.ts
  src/apis/payments/payments.module.ts
  src/apis/payments/payments.service.ts
  src/app.module.ts
Labels: enhancement

#8 feat: common req-page-dto
  src/commons/dto/page-req.dto.ts
Labels: enhancement

#9 feat: credit-history create, find
  .gitignore
  src/apis/creditHistories/credit-histories.controller.ts
  src/apis/creditHistories/credit-histories.module.ts
  src/apis/creditHistories/credit-histories.service.ts
  src/apis/creditHistories/dto/create-credit-history.dto.ts
  src/app.module.ts
Labels: enhancement

#10 feat: subscribe toggle, count
  src/apis/subscribes/dto/res.dto.ts
  src/apis/subscribes/dto/toggle-subscribe.dto.ts
  src/apis/subscribes/entities/subscribe.entity.ts
  src/apis/subscribes/interfaces/subscribes-service.interface.ts
  src/apis/subscribes/subscribes.controller.ts
  src/apis/subscribes/subscribes.module.ts
  src/apis/subscribes/subscribes.service.ts
  src/app.module.ts
Labels: enhancement

#11 feat: live update & findById API
  src/apis/lives/dto/create-live.dto.ts
  src/apis/lives/dto/update-live.dto.ts
  src/apis/lives/lives.controller.ts
  src/apis/lives/lives.module.ts
  src/apis/lives/lives.service.ts
  src/apis/tags/dto/create-tag.dto.ts
  src/apis/tags/tags.controller.ts
  src/apis/tags/tags.module.ts
  src/apis/tags/tags.service.ts
  src/app.module.ts
Labels: enhancement

#5 feat: add Tag create API & fix Live create API
  src/apis/lives/dto/create-live.dto.ts
  src/apis/lives/lives.module.ts
  src/apis/lives/lives.service.ts
  src/apis/tags/dto/create-tag.dto.ts
  src/apis/tags/tags.controller.ts
  src/apis/tags/tags.module.ts
  src/apis/tags/tags.service.ts
  src/app.module.ts
Labels: enhancement

#14 feat: interest create, update
  src/apis/interests/dto/create-interests.dto.ts
  src/apis/interests/dto/update-interests.dto.ts
  src/apis/interests/interests.controller.ts
  src/apis/interests/interests.module.ts
  src/apis/interests/interests.service.ts
  src/apis/interests/interfaces/interests-service.interface.ts
  src/app.module.ts
Labels: enhancement

#15 feat: add Live turn-off logic
  src/apis/creditHistories/credit-histories.module.ts
  src/apis/lives/dto/update-live.dto.ts
  src/apis/lives/lives.controller.ts
  src/apis/lives/lives.module.ts
  src/apis/lives/lives.service.ts
Labels: enhancement

#16 feat: notice CRUD
  src/apis/notices/dto/create-notice.dto.ts
  src/apis/notices/interfaces/notices-service.interfaces.ts
  src/apis/notices/notices.controller.ts
  src/apis/notices/notices.module.ts
  src/apis/notices/notices.service.ts
  src/app.module.ts
Labels: enhancement

#17 feat: auth refresh, refreshToken, refreshStretage, refreshGuard
  src/apis/auth/auth.controller.ts
  src/apis/auth/auth.module.ts
  src/apis/auth/auth.service.ts
  src/apis/auth/guard/auth.guard.ts
  src/apis/auth/interfaces/auth-service.interface.ts
  src/apis/auth/strategies/jwt-refresh.strategy.ts
  src/commons/interfaces/context.ts
Labels: enhancement

#19 feat: refresh strategy refreshToken not found error, cookie parser
  package.json
  src/apis/auth/auth.controller.ts
  src/apis/auth/strategies/jwt-refresh.strategy.ts
  src/main.ts
Labels: enhancement

#21 feat: add Live get API & transaction
  src/apis/lives/lives.controller.ts
  src/apis/lives/lives.service.ts
Labels: enhancement

#22 feat: noticeComment CRUD
  src/apis/noticeComments/dto/notice-comment.dto.ts
  src/apis/noticeComments/entities/notice-comment.entity.ts
  src/apis/noticeComments/interfaces/notice-comment.interface.ts
  src/apis/noticeComments/notice-comment.controller.ts
  src/apis/noticeComments/notice-comment.module.ts
  src/apis/noticeComments/notice-comment.service.ts
  src/apis/notices/interfaces/notices-service.interfaces.ts
  src/apis/notices/notices.module.ts
  src/apis/users/entities/user.entity.ts
  src/app.module.ts
Labels: enhancement

#23 feat: user profile update / find
  src/apis/auth/auth.service.ts
  src/apis/users/dto/res.dto.ts
  src/apis/users/dto/update-user.dto.ts
  src/apis/users/interfaces/users-service.interface.ts
  src/apis/users/users.controller.ts
  src/apis/users/users.service.ts
Labels: enhancement

#24 feat: socket IO base
  src/apis/events/events.gateway.ts
  src/apis/events/events.module.ts
  src/app.module.ts
Labels: enhancement

#25 feat: socket room, stream event
  src/apis/events/events.gateway.ts
Labels: enhancement

#27 feat: add signup front api
  src/apis/users/dto/create-user.dto.ts
  src/apis/users/users.service.ts
  views/public/js/sign-up.js
  views/sign-up.ejs
Labels: enhancement

#30 feat: live admin-sale api
  src/apis/lives/lives.controller.ts
  src/apis/lives/lives.service.ts
Labels: enhancement

#31 feat: subscribe get-count api
  src/apis/subscribes/dto/res.dto.ts
  src/apis/subscribes/interfaces/subscribes-service.interface.ts
  src/apis/subscribes/subscribes.controller.ts
  src/apis/subscribes/subscribes.module.ts
  src/apis/subscribes/subscribes.service.ts
Labels: enhancement

#32 feat: channel get-channel api
  src/apis/channels/channels.controller.ts
  src/apis/channels/channels.service.ts
Labels: enhancement

#33 feat: add gitattributes
  .gitattributes
Labels: enhancement

#34 feat: front streaming page design
  src/apis/lives/lives.controller.ts
  src/apis/lives/lives.service.ts
  src/apis/notices/notices.controller.ts
  src/app.controller.ts
  views/public/js/streaming.js
  views/streaming.ejs
Labels: enhancement

#35 feat: accessToken header => cookie
  src/apis/auth/auth.controller.ts
  src/apis/auth/strategies/jwt-access.strategy.ts
Labels: enhancement

#36 feat: front dashboard page
  src/apis/lives/lives.controller.ts
  src/apis/lives/lives.service.ts
  views/dashboard.ejs
  views/public/css/soft-ui-dashboard.css
  views/public/js/dashboard.js
Labels: enhancement

#37 feat: add channelservice manager finduser
  src/apis/channels/channels.controller.ts
  src/apis/channels/channels.module.ts
  src/apis/channels/channels.service.ts
  src/apis/channels/dto/update-channel-manager.dto.ts
Labels: enhancement

#38 feat: add getmanager
  src/apis/channels/channels.controller.ts
  src/apis/channels/channels.service.ts
  src/apis/users/users.service.ts
Labels: enhancement

#39 feat: front-live page chatting form, btns connection
  src/apis/lives/lives.service.ts
  views/public/js/streaming.js
  views/streaming.ejs
Labels: enhancement

#40 feat: add front manger-page
  src/apis/channels/channels.controller.ts
  src/apis/channels/channels.service.ts
  src/apis/channels/dto/update-channel-manager.dto.ts
  src/apis/users/users.service.ts
  views/public/img/profile.jpg
  views/public/js/manager.js
  views/tables.ejs
Labels: enhancement

#41 feat: front live page notice comments
  src/apis/noticeComments/notice-comment.controller.ts
  src/apis/noticeComments/notice-comment.service.ts
  src/app.controller.ts
  views/public/js/streaming.js
  views/streaming.ejs
Labels: enhancement

#43 feat: socket IO chat room server & front
  src/apis/auth/guard/gateway.guard.ts
  src/apis/events/events.gateway.ts
  src/apis/events/events.module.ts
  views/public/js/chat.js
  views/streaming.ejs
Labels: enhancement

#45 feat: chat default profile
  views/public/js/chat.js
  views/streaming.ejs
Labels: enhancement

#46 feat: add subscribe check api
  src/apis/subscribes/dto/res.dto.ts
  src/apis/subscribes/subscribes.controller.ts
  src/apis/subscribes/subscribes.service.ts
  views/public/js/chat.js
  views/public/js/streaming.js
  views/streaming.ejs
Labels: enhancement

#47 fix: channel controller get-manager path
  src/apis/channels/channels.controller.ts
  views/public/js/manager.js
Labels: enhancement

#48 refactor: front live jscode refactor
  views/public/js/channel.js
  views/public/js/index.js
  views/public/js/streaming.js
Labels: refactoring

#49 feat: add socketIO room user-count
  src/apis/events/events.gateway.ts
  views/public/js/chat.js
  views/streaming.ejs
Labels: enhancement

#52 feat: add socketIO donation
  src/apis/creditHistories/credit-histories.service.ts
  src/apis/events/events.gateway.ts
  views/public/css/streaming.css
  views/public/img/star-img.png
  views/public/js/chat.js
  views/streaming.ejs
Labels: enhancement

#53 feat: add front-index route
  views/public/js/chat.js
  views/public/js/index.js
Labels: enhancement

#55 feat: file upload to s3-bucket logic
  package.json
  src/app.module.ts
  src/uploads/multer.options.factory.ts
  src/uploads/uploads.controller.ts
  src/uploads/uploads.module.ts
  src/uploads/uploads.service.ts
Labels: enhancement

#56 feat: front-live page btns
  src/apis/channels/channels.service.ts
  views/index.ejs
  views/public/js/streaming.js
  views/streaming.ejs
Labels: enhancement

#57 feat: add billing page
  src/apis/creditHistories/credit-histories.controller.ts
  src/apis/creditHistories/credit-histories.service.ts
  views/billing.ejs
  views/public/js/billing.js
Labels: enhancement

#59 feat: get channel monthly income api
  src/apis/lives/lives.controller.ts
  src/apis/lives/lives.service.ts
  src/commons/dto/date-req.dto.ts
  views/dashboard.ejs
  views/public/js/dashboard.js
Labels: enhancement

#60 fix: add number to money string func
  views/public/js/dashboard.js
Labels: fix

#62 refactor: delete socketIO login, add streaming-page getUserData
  src/apis/events/events.gateway.ts
  src/apis/uploads/multer.options.factory.ts
  src/apis/uploads/uploads.controller.ts
  src/apis/uploads/uploads.module.ts
  src/apis/uploads/uploads.service.ts
  src/app.module.ts
  views/public/js/chat.js
Labels: enhancement

#63 feat: add live stream start api & socket IO event & front hls stream
  src/apis/events/events.gateway.ts
  src/apis/lives/lives.controller.ts
  src/apis/lives/lives.module.ts
  src/apis/lives/lives.service.ts
  views/public/js/streaming-control.js
  views/streaming-control.ejs
Labels: enhancement

#65 feat: add live start onAir false => true
  src/apis/lives/entities/live.entity.ts
  src/apis/lives/lives.controller.ts
  src/apis/lives/lives.service.ts
Labels: enhancement

#66 feat: add live-admin-control api
  src/apis/lives/lives.controller.ts
  src/apis/lives/lives.service.ts
Labels: enhancement

#67 fix: add ejs includes like side navbar
  views/billing.ejs
  views/channel.ejs
  views/dashboard.ejs
  views/includes/header-navbar.ejs
  views/includes/side-navbar.ejs
  views/index.ejs
  views/profile.ejs
  views/sign-in.ejs
  views/sign-up.ejs
  views/streaming-control.ejs
  views/tables.ejs
Labels: fix

#68 feat: front/streaming page video player added
  views/public/js/chat.js
  views/public/js/streaming.js
  views/streaming.ejs
Labels: enhancement

#70 feat: front steraming-control-onAir
  src/apis/lives/lives.service.ts
  views/public/js/streaming-control.js
Labels: enhancement

#72 feat: channel for user page
  src/apis/channels/channels.service.ts
  src/app.controller.ts
  views/includes/side-navbar.ejs
  views/my-channel.ejs
  views/public/js/dashboard.js
  views/public/js/my-channel.js
Labels: enhancement

#73 feat: add live-closeOBS-api
  src/apis/lives/lives.controller.ts
  src/apis/lives/lives.service.ts
Labels: enhancement

#74 fex: front index js card margin-bottom
  views/public/js/index.js
Labels: enhancement

#75 fix: live income logic
  src/apis/lives/lives.controller.ts
  src/apis/lives/lives.service.ts
Labels: fix

#77 feat: add video duration event
  views/includes/side-navbar.ejs
  views/public/css/video.css
  views/public/img/coin.jpg
  views/public/js/channel.js
  views/public/js/chat.js
  views/public/js/my-channel.js
  views/public/js/streaming.js
  views/streaming.ejs
Labels: enhancement

#79 feat: close obs transaction & socketIO endlive
  src/apis/channels/channels.service.ts
  src/apis/creditHistories/credit-histories.service.ts
  src/apis/events/events.gateway.ts
  src/apis/lives/lives.service.ts
  views/public/js/chat.js
  views/public/js/streaming-control.js
  views/public/js/streaming.js
  views/streaming.ejs
Labels: enhancement

#80 feat: add subscribe channel api, subscribe nav
  src/apis/channels/channels.controller.ts
  src/apis/channels/channels.service.ts
  views/includes/subscribe-side.ejs
  views/index.ejs
Labels: enhancement

#81 feat: add logo, default profile img
  views/includes/side-navbar.ejs
  views/includes/subscribe-side.ejs
  views/public/img/logo.png
  views/public/img/profile.jpg
Labels: enhancement

#82 feat: add alert entity, create, find, update api
  src/apis/alerts/alerts.controller.ts
  src/apis/alerts/alerts.module.ts
  src/apis/alerts/alerts.service.ts
  src/apis/alerts/entities/alert.entity.ts
  src/apis/alerts/interfaces/alerts-service.interface.ts
  src/apis/users/entities/user.entity.ts
  src/app.module.ts
Labels: enhancement

#83 feat: add live start alert
  src/apis/alerts/alerts.service.ts
  src/apis/alerts/interfaces/alerts-service.interface.ts
  src/apis/lives/lives.module.ts
  src/apis/lives/lives.service.ts
  src/apis/users/users.service.ts
Labels: enhancement

#84 Feat/live thumbnail
  src/apis/lives/entities/live.entity.ts
  src/apis/lives/lives.controller.ts
  src/apis/lives/lives.service.ts
  views/public/js/channel.js
Labels: enhancement

#87 refactor: live start event streamer array => room
  src/apis/alerts/alerts.service.ts
  src/apis/events/events.gateway.ts
  src/apis/events/interfaces/events-gateway.interface.ts
  src/apis/lives/lives.service.ts
  src/apis/users/users.service.ts
  views/public/js/streaming-control.js
Labels: enhancement

#90 Feat/dummy user create
  make_dummies/create.dummies.js
  package.json
  src/apis/lives/lives.service.ts
  src/apis/subscribes/subscribes.controller.ts
  src/apis/subscribes/subscribes.service.ts
  src/apis/users/users.service.ts
  src/commons/filter/http-exception.filter.ts
Labels: enhancement

#91 style: delete test code like console.log
  src/apis/auth/auth.controller.ts
  src/apis/channels/channels.controller.ts
  src/apis/channels/channels.service.ts
  src/apis/creditHistories/credit-histories.controller.ts
  src/apis/events/events.gateway.ts
  src/apis/lives/lives.controller.ts
  src/apis/lives/lives.service.ts
  src/apis/noticeComments/notice-comment.controller.ts
  src/apis/subscribes/subscribes.service.ts
  src/apis/tags/tags.service.ts
  views/public/js/billing.js
  views/public/js/channel.js
  views/public/js/chat.js
  views/public/js/index.js
  views/public/js/manager.js
  views/public/js/my-channel.js
  views/public/js/sign-in.js
  views/public/js/sign-up.js
  views/public/js/streaming-control.js
  views/public/js/streaming.js
Labels: style

#92 refactor: streaming-control.js
  views/public/js/streaming-control.js
Labels: refactoring

#94 style: change front design & fix some text
  views/billing.ejs
  views/channel.ejs
  views/dashboard.ejs
  views/index.ejs
  views/my-channel.ejs
  views/profile.ejs
  views/public/js/streaming-control.js
  views/public/js/streaming.js
  views/sign-in.ejs
  views/sign-up.ejs
  views/streaming-control.ejs
  views/streaming.ejs
  views/tables.ejs
Labels: style

#95 style: change code style & delete test code
  src/apis/lives/lives.controller.ts
  src/apis/lives/lives.service.ts
Labels: style

#97 fix/ front-mainpage, streaming-control
  src/apis/lives/lives.service.ts
  views/public/js/index.js
  views/streaming-control.ejs
Labels: fix

#98 fix: redis password
  src/app.module.ts
Labels: fix

#99 feat: add streaming-control-donation
  .gitignore
  src/apis/lives/lives.service.ts
  views/public/js/streaming-control.js
Labels: enhancement

#100 fix: play time null bug fix
  views/public/js/dashboard.js
Labels: enhancement

#101 fix: sign-in/up page design
  src/app.module.ts
  views/sign-in.ejs
  views/sign-up.ejs
Labels: fix
