Repository cooderyg/streaming-platform, pull requests merged in 2023-09, with the labels that each got.

#103 feat: add video-live-sync option & video autoplay/muted
  views/public/css/video.css
  views/public/js/streaming.js
  views/streaming.ejs
Labels: enhancement

#105 feat: add live search
  src/apis/channels/channels.service.ts
  src/apis/lives/entities/live.entity.ts
  src/apis/lives/lives.controller.ts
  src/apis/lives/lives.service.ts
  src/app.controller.ts
  views/includes/header-navbar.ejs
  views/public/css/search.css
  views/public/js/search.js
  views/search.ejs
Labels: enhancement

#107 feat: channel-donation-ranking
  src/apis/creditHistories/credit-histories.controller.ts
  src/apis/creditHistories/credit-histories.service.ts
  views/channel.ejs
  views/my-channel.ejs
  views/public/js/channel.js
  views/public/js/my-channel.js
  views/replay.ejs
Labels: enhancement

#108 feat: add alert-read
  views/includes/header-navbar.ejs
Labels: enhancement

#111 feat: login redirect & streaming page notice
  views/includes/header-navbar.ejs
  views/includes/subscribe-side.ejs
  views/public/js/chat.js
  views/public/js/sign-in.js
  views/public/js/streaming.js
  views/streaming.ejs
Labels: enhancement

#112 style: add alert types
  src/apis/alerts/alerts.controller.ts
  src/apis/alerts/alerts.service.ts
  src/apis/alerts/dto/res.dto.ts
Labels: enhancement

#113 style: add auth type
  src/apis/auth/auth.controller.ts
  src/apis/auth/auth.service.ts
  src/commons/dto/message-res.dto.ts
Labels: style

#114 style: add channels-service interface & channel type
  src/apis/channels/channels.controller.ts
  src/apis/channels/channels.service.ts
  src/apis/channels/interfaces/channels-service.interface.ts
  src/commons/dto/ok-res.dto.ts
Labels: style

#115 style: add chats-service interface & chat type
  src/apis/chats/chats.controller.ts
  src/apis/chats/chats.service.ts
  src/apis/chats/interfaces/chats-service.interface.ts
Labels: style

#116 feat: chat-abuse-filtering
  views/public/js/chat.js
  views/public/js/sign-up.js
Labels: enhancement

#117 style: add credit-histories interface & type
  src/apis/creditHistories/credit-histories.controller.ts
  src/apis/creditHistories/credit-histories.service.ts
  src/apis/creditHistories/interfaces/creditHistories-service.interface.ts
Labels: style

#118 style: add lives-service interface & live type
  src/apis/lives/dto/addThumbnail.dto.ts
  src/apis/lives/dto/res.dto.ts
  src/apis/lives/interfaces/lives-service.interface.ts
  src/apis/lives/lives.controller.ts
  src/apis/lives/lives.service.ts
Labels: style

#119 style: add payments-service interface
  src/apis/payments/interfaces/payments-service.interface.ts
  src/apis/payments/payments.service.ts
Labels: style

#120 style: add subscribe type
  src/apis/subscribes/subscribes.controller.ts
Labels: style

#121 style: add tags-service interface & type
  src/apis/tags/interfaces/tags-service.interface.ts
  src/apis/tags/tags.controller.ts
  src/apis/tags/tags.service.ts
Labels: style

#122 style: add updaload interface & type
  src/apis/uploads/dto/res.dto.ts
  src/apis/uploads/interfaces/uploads-service.interface.ts
  src/apis/uploads/uploads.controller.ts
  src/apis/uploads/uploads.service.ts
Labels: style

#123 style: add users-service interface & user type
  src/apis/users/dto/res.dto.ts
  src/apis/users/interfaces/users-service.interface.ts
  src/apis/users/users.controller.ts
  src/apis/users/users.service.ts
Labels: style

#125 style: add notice-comment type & interface
  src/apis/noticeComments/notice-comment.controller.ts
  src/apis/noticeComments/notice-comment.service.ts
Labels: style

#126 feat: passport kakao login api
  package.json
  src/apis/auth/auth.controller.ts
  src/apis/auth/auth.module.ts
  src/apis/auth/auth.service.ts
  src/apis/auth/dto/login.dto.ts
  src/apis/auth/guard/auth.guard.ts
  src/apis/auth/interfaces/auth-service.interface.ts
  src/apis/auth/strategies/jwt-access.strategy.ts
  src/apis/auth/strategies/jwt-refresh.strategy.ts
  src/apis/auth/strategies/jwt-social-kakao.strategy.ts
  src/apis/users/users.service.ts
  src/commons/decorators/user.decorator.ts
  views/public/img/kakao_login_large_wide.png
  views/public/js/sign-in.js
  views/sign-in.ejs
Labels: enhancement

#127 feat: add passport google strategy
  package.json
  src/apis/auth/auth.controller.ts
  src/apis/auth/auth.module.ts
  src/apis/auth/guard/auth.guard.ts
  src/apis/auth/strategies/jwt-social-google.strategy.ts
  src/apis/auth/strategies/jwt-social-kakao.strategy.ts
  views/public/img/google_icon.png
  views/public/img/kakao_icon.png
  views/public/img/kakao_login_large_wide.png
  views/public/js/sign-in.js
  views/sign-in.ejs
Labels: enhancement

#128 style: fix social-passport file, var names
  src/apis/auth/auth.controller.ts
  src/apis/auth/auth.module.ts
  src/apis/auth/auth.service.ts
  src/apis/auth/strategies/social-google.strategy.ts
  src/apis/auth/strategies/social-kakao.strategy.ts
  views/public/js/sign-in.js
Labels: style

#130 feat/chat-save & load
  .gitignore
  package.json
  src/apis/chats/chats.controller.ts
  src/apis/chats/chats.module.ts
  src/apis/chats/chats.service.ts
  src/apis/chats/dto/create-chat.dto.ts
  src/apis/chats/interfaces/chats-service.interface.ts
  src/apis/chats/schemas/chat.schema.ts
  src/apis/events/events.gateway.ts
  src/apis/events/events.module.ts
  src/app.module.ts
  views/public/js/chat.js
Labels: enhancement

#135 feat: search chat in dashboard by email
  src/apis/chats/chats.controller.ts
  src/apis/chats/chats.module.ts
  src/apis/chats/chats.service.ts
  src/apis/lives/lives.service.ts
  views/dashboard.ejs
  views/public/js/dashboard.js
Labels: enhancement

#136 feat: search chat auto scroll
  src/apis/chats/chats.controller.ts
  src/apis/chats/chats.service.ts
  views/public/js/dashboard.js
Labels: enhancement

#137 fix: dashboard intersectionObserver another email error
  views/public/js/dashboard.js
Labels: fix

#142 fix: change frontend UI & bug fix
  views/billing.ejs
  views/channel.ejs
  views/dashboard.ejs
  views/includes/head.ejs
  views/includes/header-navbar.ejs
  views/includes/side-navbar.ejs
  views/index.ejs
  views/my-channel.ejs
  views/profile.ejs
  views/public/js/billing.js
  views/public/js/channel.js
  views/public/js/my-channel.js
  views/replay.ejs
  views/search.ejs
  views/sign-in.ejs
  views/sign-up.ejs
  views/streaming-control.ejs
  views/streaming.ejs
  views/tables.ejs
Labels: fix, style

#147 feat: add live start not found error
  src/apis/lives/lives.service.ts
Labels: enhancement

#149 feat: add alert socket IO
  src/apis/events/events.gateway.ts
  src/apis/lives/lives.service.ts
  src/apis/subscribes/subscribes.controller.ts
  src/apis/subscribes/subscribes.service.ts
  views/billing.ejs
  views/channel.ejs
  views/dashboard.ejs
  views/includes/header-navbar.ejs
  views/index.ejs
  views/my-channel.ejs
  views/replay.ejs
  views/search.ejs
  views/tables.ejs
Labels: enhancement

#154 feat: add bull queue
  .gitignore
  package.json
  src/apis/channels/channels.controller.ts
  src/apis/lives/lives.controller.ts
  src/apis/lives/lives.module.ts
  src/apis/lives/lives.processor.ts
  src/apis/lives/lives.service.ts
  src/apis/subscribes/subscribes.module.ts
  src/apis/users/interfaces/users-service.interface.ts
  src/apis/users/users.service.ts
  src/app.module.ts
Labels: enhancement

#155 feat: add Elastic Search
  elk/logstash/mysql-connector-java-8.0.28.jar
  package.json
  src/apis/channels/channels.service.ts
  src/apis/lives/lives.controller.ts
  src/apis/lives/lives.module.ts
  src/apis/lives/lives.service.ts
  src/apis/lives/lives.subscriber.ts
  src/app.module.ts
  views/public/css/search.css
  views/public/js/index.js
  views/public/js/search.js
  views/search.ejs
Labels: enhancement

#157 feat: add docker & docker-compose
  .dockerignore
  .gitignore
  Dockerfile
  docker-compose.yaml
  package.json
  src/apis/events/events.gateway.ts
  src/app.module.ts
  views/includes/header-navbar.ejs
  views/public/js/chat.js
  views/public/js/streaming.js
Labels: enhancement

#160 feat: add custom-exception
  src/apis/lives/lives.service.ts
  src/commons/filter/custom-exception.filter.ts
  src/commons/filter/http-exception.filter.ts
  src/main.ts
Labels: enhancement

#162 feat: add elastic search exception
  src/apis/lives/lives.service.ts
  src/apis/lives/lives.subscriber.ts
Labels: enhancement

#165 feat: add alert null message
  views/includes/header-navbar.ejs
  views/my-channel.ejs
Labels: enhancement

#166 feat: add alert login
  views/includes/header-navbar.ejs
Labels: enhancement

#168 fix: custom filter fix
  src/commons/filter/custom-exception.filter.ts
Labels: fix

#171 fix: streaming page notice delete
  views/public/css/streaming.css
  views/public/js/streaming.js
  views/streaming.ejs
Labels: fix

#172 fix: notice page & create comment page
  src/apis/lives/lives.controller.ts
  src/apis/lives/lives.module.ts
  src/apis/lives/lives.service.ts
  src/apis/lives/lives.subscriber.ts
  src/apis/noticeComments/notice-comment.service.ts
  src/apis/notices/notices.service.ts
  src/app.controller.ts
  views/comment.ejs
  views/notice.ejs
  views/public/js/comment.js
  views/public/js/notice.js
Labels: enhancement, fix

#174 fix: replay notice delete
  views/public/js/replay.js
  views/public/js/streaming.js
  views/replay.ejs
Labels: fix

#175 feat: add href in my-channel for notice & cmt
  views/my-channel.ejs
  views/public/js/my-channel.js
Labels: enhancement

#176 feat: add href in channel page
  views/channel.ejs
  views/my-channel.ejs
  views/public/js/channel.js
Labels: enhancement

#179 fix: clip side-nav => header-nav
  views/includes/header-navbar.ejs
  views/includes/subscribe-side.ejs
Labels: fix

#180 feat: create comment & design fix
  views/comment.ejs
  views/notice.ejs
  views/public/js/channel.js
  views/public/js/comment.js
  views/public/js/my-channel.js
Labels: enhancement

#182 feat: add front payment cancel
  views/public/js/billing.js
Labels: enhancement

#183 feat: add front donation validate
  views/public/js/chat.js
Labels: enhancement
